<?php

return [
    'DOMAIN' => env('DOMAIN', null),

    'SHARING_DOMAIN' => env('SHARING_DOMAIN'),

    'NODEJS_DOMAIN' => env('NODEJS_DOMAIN'),
    'CHAT_DOMAIN' => env('CHAT_DOMAIN'),
    'NODEJS_PORT' => env('NODEJS_PORT', 2052),

    'USER_IS_ONLINE_MINUTES' => env('USER_IS_ONLINE_MINUTES', 5),
    'USER_WAS_RECENTLY_MINUTES' => env('USER_WAS_RECENTLY_MINUTES', 120),
    'REFRESH_LAST_ACTIVE_SECONDS' => env('REFRESH_LAST_ACTIVE_SECONDS', 120),
    'REFRESH_ADDRESS_FOR_LAT_LNG_CHANGE_METERS' => env('REFRESH_ADDRESS_FOR_LAT_LNG_CHANGE_METERS', 200),
    'DISTANCE_METERS_DIFFERENCE_RELOAD_USERS_AROUND' => env('DISTANCE_METERS_DIFFERENCE_RELOAD_USERS_AROUND', 500),
    'REFRESH_USERS_AROUND_INTERVAL_SECONDS' => env('REFRESH_USERS_AROUND_INTERVAL_SECONDS', 600),
    'PRE_SEARCH_USERS_AROUND_KM' => env('PRE_SEARCH_USERS_AROUND_KM', 50),

    'MAX_EVENT_PHOTOS' => env('MAX_EVENT_PHOTOS', 4),
    'MAX_EVENT_VIDEOS' => env('MAX_EVENT_VIDEOS', 4),
    'MAX_PUBLIC_PICTURES_AMOUNT' => env('MAX_PUBLIC_PICTURES_AMOUNT', 4),
    'MAX_PUBLIC_VIDEOS_AMOUNT' => env('MAX_PUBLIC_VIDEOS_AMOUNT', 4),

    'FREE_EVENTS_LIMIT' => env('FREE_EVENTS_LIMIT', 99),
    'FREE_FAVORITES_LIMIT' => env('FREE_FAVORITES_LIMIT', 99),
    'FREE_BLOCKS_LIMIT' => env('FREE_BLOCKS_LIMIT', 99),

    'LOAD_EVENTS_PER_DATE_INITIAL' => env('LOAD_EVENTS_PER_DATE_INITIAL', 3),
    'LOAD_EVENTS_PER_DATE_NEXT' => env('LOAD_EVENTS_PER_DATE_NEXT', 15),
    'LOAD_EVENTS_DATES_PER_PAGE' => env('LOAD_EVENTS_DATES_PER_PAGE', 10),

    'LOAD_USERS_AROUND_LIMIT' => env('LOAD_USERS_AROUND_LIMIT', 48),
    'LOAD_VISITORS_LIMIT' => env('LOAD_VISITORS_LIMIT', 24),
    'LOAD_TAPS_LIMIT' => env('LOAD_TAPS_LIMIT', 24),
    'LOAD_CHAT_MESSAGES_LIMIT' => env('LOAD_CHAT_MESSAGES_LIMIT', 70),
    'LOAD_API_CHAT_MESSAGES_LIMIT' => env('LOAD_API_CHAT_MESSAGES_LIMIT', 70),
    'LOAD_CHAT_WINDOWS_LIMIT' => env('LOAD_CHAT_WINDOWS_LIMIT', 100),

    'MINIMUM_AGE' => env('MINIMUM_AGE', 18),

    'MESSAGES_SPAM_24_HOURS_LIMIT' => env('MESSAGES_SPAM_24_HOURS_LIMIT', 100),
    'MESSAGES_SPAM_1_HOUR_LIMIT' => env('MESSAGES_SPAM_1_HOUR_LIMIT', 50),
    'MESSAGES_SPAM_EMAIL_BOUNCED_LIMIT' => env('MESSAGES_SPAM_EMAIL_BOUNCED_LIMIT', 1),

    'RUSH_STRIPS_LIMIT' => env('RUSH_STRIPS_LIMIT', 1),
    'RUSH_FAVORITES_LIMIT' => env('RUSH_FAVORITES_LIMIT', 5),

    'ONESIGNAL_APP_ID' => env('ONESIGNAL_APP_ID'),

    'TELEGRAM_BOT_TOKEN' => env('TELEGRAM_BOT_TOKEN'),
    'TELEGRAM_CHAT_ID' => env('TELEGRAM_CHAT_ID'),

    'ITUNES_SSLVERSION' => env('ITUNES_SSLVERSION', ''),
    'ITUNES_SSLCERT' => env('ITUNES_SSLCERT', ''),
    'ITUNES_SSLKEYPASSWD' => env('ITUNES_SSLKEYPASSWD', ''),
    'ITUNES_SSLKEY' => env('ITUNES_SSLKEY', ''),

    'ADMIN_EMAIL' => env('ADMIN_EMAIL'),
    'ADMIN_NAME' => env('ADMIN_NAME'),

    'SPARKPOST_EU_SECRET' => env('SPARKPOST_EU_SECRET'),
    'MAIL_FROM_NAME' => env('MAIL_FROM_NAME'),
    'MAIL_FROM_ADDRESS' => env('MAIL_FROM_ADDRESS'),

    'RECAPTCHA_SITE_KEY' => env('RECAPTCHA_SITE_KEY'),
    'RECAPTCHA_PRIVATE_KEY' => env('RECAPTCHA_PRIVATE_KEY'),
    'RECAPTCHA_SCORE' => env('RECAPTCHA_SCORE', 0.5),
    'GMAP_API_KEY' => env('GMAP_API_KEY'),
    'MAP_PROVIDER' => env('MAP_PROVIDER', 'osm'),

    'SightengineClient_USER' => env('SightengineClient_USER'),
    'SightengineClient_PSW' => env('SightengineClient_PSW'),
    'START_NUDITY_RATING' => env('START_NUDITY_RATING', 0.4),

    'BB_USER_ID' => env('BB_USER_ID'),
    'APP_DOMAIN' => env('APP_DOMAIN'),

    'SERVER_OS' => env('SERVER_OS'),
    'SERVICE_WORKER_ENABLED' => env('SERVICE_WORKER_ENABLED', true),
    'ECHO_ENABLED' => env('ECHO_ENABLED', true),

    'ANTI_SPAM_ENABLED' => env('ANTI_SPAM_ENABLED', true),
];
